#!/bin/bash

filename=""

while getopts ":n:" opt; do
  case $opt in
    n)
      filename=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$filename" ]; then
  echo "Checking all .py files"
  pycodestyle *.py
else
  echo "Checking $filename"
  pycodestyle "$filename"
fi
